### ISSUE TITLE
working, but I get errors from serialport

### ISSUE THREAD

**Issue by Averelll** [rfxcom/node-rfxcom#53]
I have node-rfxcom (and node-red-contrib-rfxcom) working. But when I start up even the most simple nodejs script, serialport gives me the most horrendous error message, even though afte this it does work. I have tried newer versions of serialport, I tried to use the npm install --build-from-source for serialport, but I always get the same huge error message. I can try to copy it, but I saw when I tried to raise the issue on the serialport page, it will cut off the lines.
I get it both on Debian Linux, and on raspberry pi (and in the error log of node-red). Running the latest node-red, and node v6.22.

**Comment by Averelll** [comment]
I was a bit too hasty :) Seem it is a known issue, with serialport on newer version of node.js, and just tells me something is deprecated. see https://github.com/EmergingTechnologyAdvisors/node-serialport/pull/777/commits
Should be fixable by using serialport4.x. Would mean a small change in opening a serial port (syntax changed). Any chances of picking this up?

**Comment by Averelll** [comment]
Ok, I fixed my issue by using serialport v 4.01. I changed the new serialport to use the new syntax (autoOpen instead of openimmediately etc.). 
Not sure if there is a reason not to use the new version of serialport for everybody?

**Comment by maxwellhadley** [comment]
Sorry to be so long getting back, been busy elsewhere...
I see you are running a 6.x version of NodeJS, and node-RED still recommend keeping to a 4.x LTS release. However, serialport 4.01 should work with that OK as well. However I'm still not clear exactly what you think caused the error message in your original issue report. Could you clarify this, please? Any chance of raising a PR implementing your changes to use serialport 4.0.1? This should be OK for everyone as it is supported all the way back to NodeJS 0.10.x

**Comment by johnburton** [comment]
Has this been updated yet?
I modified my local copy to use serialport : "3.x" as it solves the issue but version 4.x of serialport seems to have some breaking api changes. Would you be interested in a trivial pull request to move serialport to 3.x?

**Comment by maxwellhadley** [comment]
Thanks, but don't bother with the PR.  I'm currently working on the add-blinds1 branch, which is nearly done. Moving to an up to date serialport is next on the list - however this will involve ensuring the operation of connecting & disconnecting the RFXtrx433 is handled properly on Windows, Linux, and Mac OS X, not just that the port is opened and communicates OK. There are also a couple of recently-deprecated nodeJS API's which are currently used & should be removed, so I'll probably enforce node version >=4 at the same time, leaving node 0.10 & 0.12 users on serialport 2.x. This will be a major version number bump!

**Comment by johnburton** [comment]
Ah no problem, and thanks for the useful library

**Comment by maxwellhadley** [comment]
You're welcome!

**Comment by maxwellhadley** [comment]
Serialport now updated to 4.* - tested with 4.0.7
